CC=gcc -std=gnu99
FLAGS= -Wall -Wextra
L= -lm

binary_search_iterative: binary_search_iterative.c
	$(CC) $(FLAGS) $(L) -o binary_search_iterative binary_search_iterative.c

binary_search_recursive: binary_search_recursive.c
	$(CC) $(FLAGS) $(L) -o binary_search_recursive binary_search_recursive.c

linear_search_iterative: linear_search_iterative.c
	$(CC) $(FLAGS) $(L) -o linear_search_iterative linear_search_iterative.c

linear_search_recursive: linear_search_recursive.c
	$(CC) $(FLAGS) $(L) -o linear_search_recursive linear_search_recursive.c


