CC=gcc
FLAGS= -Wall -Wextra
L= -lm

binary_search_iterative: binary_search_iterative.c
	$(CC) $(FLAGS) $(L) -o binary_search_iterative binary_search_iterative.c

binary_search_recursive: binary_search_recursive.c
	$(CC) $(FLAGS) $(L) -o binary_search_recursive binary_search_recursive.c
