CC=gcc -std=gnu99
FLAGS= -Wall -Wextra
L= -lm

insertion_sort_iterative: insertion_sort_iterative.c
	$(CC) $(FLAGS) $(L) -o insertion_sort_iterative insertion_sort_iterative.c

#insertion_sort_recursive: insertion_sort_recursive.c
#	$(CC) $(FLAGS) $(L) -o insertion_sort_recursive insertion_sort_recursive.c
#
#linear_search_iterative: linear_search_iterative.c
#	$(CC) $(FLAGS) $(L) -o linear_search_iterative linear_search_iterative.c
#
#linear_search_recursive: linear_search_recursive.c
#	$(CC) $(FLAGS) $(L) -o linear_search_recursive linear_search_recursive.c


