CC=gcc -std=gnu99
FLAGS= -Wall -Wextra
L= -lm

insertion_sort_iterative: insertion_sort_iterative.c
	$(CC) $(FLAGS) $(L) -o insertion_sort_iterative insertion_sort_iterative.c

insertion_sort_recursive: insertion_sort_recursive.c
	$(CC) $(FLAGS) $(L) -o insertion_sort_recursive insertion_sort_recursive.c

merge_sort_iterative: merge_sort_iterative.c
	$(CC) $(FLAGS) $(L) -o merge_sort_iterative merge_sort_iterative.c

merge_sort_recursive: merge_sort_recursive.c
	$(CC) $(FLAGS) $(L) -o merge_sort_recursive merge_sort_recursive.c



