CC=gcc -std=gnu99
FLAGS= -Wall -Wextra -Wfloat-equal -Wundef -Wshadow -Wpointer-arith -Wcast-align -Wstrict-prototypes -Wwrite-strings -Waggregate-return -g
L= -lm

default: reader.c
	clear && $(CC) $(FLAGS) -o reader.o reader.c
